# Generated by Django 4.2.6 on 2023-10-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='expenses.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='expenses.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenseshare',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expenseshare',
            name='user',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='paid_by',
            new_name='payer',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='ExpenseShare',
        ),
    ]
